local ADDON_NAME, OneWoW = ...

local OneWoW_GUI = OneWoW_GUI

local DB = OneWoW_GUI.DB

local DEFAULTS = {
    language = GetLocale(),
    theme = "green",
    font = "default",
    fontSizeOffset = 0,
    minimap = {
        hide = false,
        minimapPos = 220,
        theme = "horde",
    },
    minimapLaunchers = {},
    moneyDisplay = {
        useLetters = false,
        useRegionalNumbers = true,
        useWhiteValues = true,
    },
    mainFrameSize = {
        width = 1400,
        height = 900,
    },
    lastModuleTab = "home",
    lastSubTabs = {},
    debugTrace = false,
    portalHub = {
        escEnabled = true,
        randomHearthstone = true,
        showAll = true,
        showAllOnEsc = false,
        showSeasonal = true,
        showDalaranHearth = true,
        showGarrisonHearth = true,
        showFlightWhistle = true,
        showHousingPortal = true,
        escShowZoneNotes = true,
        escHideZoneNotesWhenEmpty = false,
        escShowAlerts = true,
        escPortalsEnabled = true,
        escShowCharacterInfo = true,
        escPanelsSide = "left",
        escPortalsSide = "right",
        allFavorites = {},
        escFavorites = {},
        customItems = {},
        iconSize = 36,
        escIconSize = 32,
        gridColumns = 8,
    },
    instanceStatsEsc = { enabled = false },
    instanceStatsPosition = {},
    settings = {
        overlays = {
            general = { enabled = true },
            consumables = {
                enabled          = false,
                icon             = "VignetteEvent-SuperTracked",
                position         = "TOPRIGHT",
                scale            = 1.0,
                alpha            = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            itemlevel = {
                enabled = false,
                position = "TOPRIGHT",
                useQualityColors = false,
                applyToVendorItems = true,
                applyToAuctionHouse = false,
                fontSize = 10,
                showPetLevel = true,
                showContainerSlots = true,
            },
            knownitems = {
                enabled = false,
                icon = "warband-completed-icon",
                position = "TOPRIGHT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            unknownitems = {
                enabled = false,
                icon = "Warfronts-BaseMapIcons-Horde-Workshop-Minimap",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            housingdecor = {
                enabled = false,
                icon = "shop-icon-housing-beds-selected",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            mounts = {
                enabled = false,
                icon = "icon-mount",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            pets = {
                enabled = false,
                icon = "icon-pet",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            quest = {
                enabled = false,
                icon = "Quest-Campaign-Available",
                position = "CENTER",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            reagents = {
                enabled = false,
                icon = "Bonus-Objective-Star",
                position = "TOPRIGHT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            recipe = {
                enabled = false,
                icon = "icon-recipe",
                position = "BOTTOMRIGHT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            soulbound = {
                enabled = false,
                icon = "VignetteKill",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            toys = {
                enabled = false,
                icon = "icon-toy",
                position = "BOTTOMRIGHT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            warbound = {
                enabled = false,
                icon = "warbands-icon",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
                includeWUE = true,
            },
            wue = {
                enabled = false,
                icon = "warband-completed-icon",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            boe = {
                enabled = false,
                icon = "icon-flag",
                position = "TOPRIGHT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            junk = {
                enabled = false,
                icon = "bags-junkcoin",
                position = "CENTER",
                scale = 1.5,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
                showInTooltip = true,
                includeGreyItems = false,
            },
            protected = {
                enabled = false,
                icon = "soulbinds_tree_conduit_icon_protect",
                position = "CENTER",
                scale = 1.5,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
                showInTooltip = true,
            },
            upgrade = {
                enabled = false,
                icon = "Professions-Icon-Quality-Tier3-Small",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
                mode = "ILVL",
                pawnEnforceReqLevel = true,
                showInTooltip = false,
                tooltipDetail = "FULL",
                tooltipOnlyUpgrade = false,
                tooltipShowSkipReason = false,
                tooltipShowAlts = true,
                tooltipIgnoreSoulbound = false,
                tooltipAltLimit = 10,
                tooltipAltWhitelistEnabled = false,
                tooltipAltWhitelist = {},
                showPawnPrompt = true,
                altSpecMatch = false,
                selfSpecMatch = false,
            },
            transmog = {
                enabled = false,
                icon = "Warfronts-BaseMapIcons-Horde-Workshop-Minimap",
                position = "TOPLEFT",
                scale = 1.0,
                alpha = 1.0,
                applyToVendorItems = false,
                applyToAuctionHouse = false,
            },
            integrations = {
                arkinventory = { enabled = true },
                baganator    = { enabled = true },
                bagnon       = { enabled = true },
                betterbags   = { enabled = true },
                elvui        = { enabled = true },
                onewow_bags  = { enabled = true },
            },
        },
        -- Toast runtime config (relocated from the legacy db.global.toasts
        -- root in migration v5). "anchor" is a storage-only id — not in the
        -- SettingsFeatureRegistry catalog; its x/y are dynamic keys written
        -- on drag.
        toastalerts = {
            general        = { enabled = false },
            detectiontypes = {
                enabled = false,
                mounts  = false,
                pets    = false,
                toys    = false,
                recipes = false,
                recipesOnlyMyProfessions = false,
                tmogs   = false,
                suppressBlizzardAlerts = false,
                sound   = SOUNDKIT.READY_CHECK,
            },
            instances      = { enabled = false, sound = 0 },
            notealerts     = {
                enabled = false,
                npcs    = false,
                players = false,
                zones   = false,
                items   = false,
                sound   = SOUNDKIT.ACHIEVEMENT_MENU_OPEN,
            },
            upgrades       = { enabled = false },
            anchor         = { visible = true, locked = false },
        },
        tooltips = {
            general = { enabled = true },
            technicalids = {
                enabled = false,
                showItemID = true,
                showSpellID = true,
                showNpcID = true,
                showAchievementID = true,
                showQuestID = true,
                showCurrencyID = true,
                showMountID = true,
                showPetID = true,
                showEnchantID = true,
                showIconID = true,
                showExpansionID = true,
                showSetID = true,
                showDecorEntryID = true,
                showRecipeID = true,
                showEquipmentSetID = true,
                showEssenceID = true,
                showConduitID = true,
                showOutfitID = true,
                showMacroID = true,
                showObjectID = true,
                showAbilityID = true,
                showAreaPoiID = true,
                showArtifactPowerID = true,
                showBonusID = true,
                showCompanionID = true,
                showCriteriaID = true,
                showGemID = true,
                showSourceID = true,
                showTalentID = true,
                showTraitDefinitionID = false,
                showTraitEntryID = false,
                showTraitNodeID = false,
                showVignetteID = true,
                showVisualID = true,
            },
            itemtracker = {
                enabled = true,
                colorByClass = true,
                characterLimit = 10,
                showAlts        = true,
                showBags        = true,
                showBank        = true,
                showEquipped    = true,
                showAuctions    = true,
                showWarbandBank = true,
                showGuildBanks  = true,
                showVendors     = true,
                showInstances   = true,
            },
            recipeknowledge = { enabled = true },
            customnotes = { enabled = true },
            enhancements = {
                removeBlizzardVendorValue = true,
            },
            talentmods = {},
            value = {
                enabled = true,
                showVendorPrice = true,
                showAHValue = true,
                ahPriceSource = "onewow",
                showTSMValue = false,
                tsmPriceString = "dbmarket",
            },
            pets = {
                enabled = true,
                showCollectionStatus = true,
                showPetInfo = true,
                showSource = true,
                showDescription = true,
                showValue = true,
                showAHValue = true,
                showItemStatus = true,
                showTechnicalIDs = true,
            },
        },
    },
    itemStatus = {},
    -- Runtime state of Integrations/ExternalTooltipSync.lua (Auctionator option
    -- backups, one-time notice flags). Machine state, not user settings — kept
    -- outside the settings funnel.
    externalTooltipSync = {
        auctionatorBackup = {},
        auctionatorPopupShown = false,
        tsmNoticeShown = false,
    },
    profiles = {},
    charProfiles = {},
    defaultProfile = "Default",
}

--- Fresh copy of the shipped defaults subtree for one settings tab
--- ("overlays", "tooltips", "toastalerts"). Used by
--- SettingsFeatureRegistry:ResetTab. Errors on unknown tab names.
---@param tabName string
---@return table
function OneWoW:GetSettingsDefaults(tabName)
    return CopyTable(DEFAULTS.settings[tabName])
end

function OneWoW:InitializeDatabase()
    -- OneWoW_DB was historically a flat root — the root WAS the global table
    -- (`self.db = { global = OneWoW_DB }`). DB:Init single mode expects
    -- root.global plus scope roots, so wrap a legacy flat SV once before
    -- Init. Shape-detected: runs once when the SV is still flat.
    local sv = OneWoW_DB
    if sv and not sv.global and next(sv) ~= nil then
        local oldData = {}
        for k, v in pairs(sv) do
            oldData[k] = v
        end
        wipe(sv)
        sv.global = oldData
    end

    self.db = DB:Init({
        addonName = ADDON_NAME,
        savedVar = "OneWoW_DB",
        defaults = { global = DEFAULTS },
    })
end
