-- OneWoW_Notes Addon File
-- OneWoW_Notes/Core/Database.lua
-- Created by MichinMuggin (Ricky)
local addonName, ns = ...

ns.DatabaseDefaults = {
    global = {
        language             = nil,
        theme                = "green",
        lastTab              = "notes",
        mainFrameSize        = nil,
        mainFramePosition    = nil,
        minimap              = { hide = false, minimapPos = 220, theme = "horde" },
        notes                = {},
        playerNotes          = {},
        npcNotes             = {},
        zoneNotes            = {},
        itemNotes            = {},
        items                = {},
        zones                = {},
        players              = {},
        npcs                 = {},
        notesCustomCategories = {},
        itemCustomCategories  = {},
        zoneCustomCategories  = {},
        playerCustomCategories = {},
        npcCustomCategories   = {},
        notePinPositions      = {},
        zonePinPositions      = {},
        trackerLists          = {},
        trackerBundledVersions = {},
        trackerGlobalProgress = {},
        guidesRoutinesCleanedUp = false,
        sortCompletedTasks    = false,
        tabSortPrefs = {
            notes   = { by = "modified", ascending = false },
            npcs    = { by = "name",     ascending = true  },
            players = { by = "name",     ascending = true  },
            zones   = { by = "name",     ascending = true  },
            items   = { by = "name",     ascending = true  },
        },
        zoneAlertsEnabled     = true,
    },
    char = {
        notes         = {},
        items         = {},
        zones         = {},
        players       = {},
        npcs          = {},
        trackerProgress = {},
        trackerDashboard = {},
        trackerActiveList = nil,
        trackerLastWeeklyReset = 0,
        trackerLastDailyReset = 0,
    },
}
