local ADDON_NAME, Addon = ...

local OneWoW_GUI = LibStub("OneWoW_GUI-1.0", true)
if not OneWoW_GUI then return end

local noArgs = {}
local unitSpellCastCommonArgs = { "unit", "castGUID", "spellID", "castBarID" }
local itemLockCommonArgs = { "bagOrSlotIdx", "slotIdx" }

Addon.Constants = {
    -- Error logger: EventRegistry name for internal subscribers (e.g. future EventMonitor correlation)
    ERROR_CAPTURE_EVENT = "OneWoW_DevTool.ErrorCaptured",
    -- Token-bucket refill rate (errors per second) before throttling capture
    ERROR_LOGGER_ERRORS_PER_SEC = 10,

    EVENT_SELECTOR_CUSTOM_BUFFER = 100,

    -- Event viewer color keys; string = OneWoW_GUI theme key, table = {r,g,b,a} for colors not in theme
    EVENT_VIEWER_COLORS = {
        TIMESTAMP = "TEXT_MUTED",
        EVENT_NAME = "TEXT_ACCENT",
        ARG_DEFAULT = "TEXT_PRIMARY",
        UNIT = { 0.4, 0.6, 0.9, 1 },
        SECRET = { 1, 0.4, 0.4, 1 },
    },
    EVENT_COLLAPSE_WINDOW = 0.2,

    -- Event viewer row layout (pixels)
    EVENT_VIEWER_ROW_HEIGHT = 14,
    EVENT_VIEWER_COL_EVENT = 280,
    EVENT_VIEWER_COL_ARGS = 260,

    -- Argument names per event (index = arg position); reference: warcraft.wiki.gg/wiki/Events
    EVENT_ARG_NAMES = {
        PLAYER_ENTERING_WORLD = {"isInitialLogin", "isReload"},
        PLAYER_LEAVING_WORLD = noArgs,
        PLAYER_LOGIN = noArgs,
        PLAYER_LOGOUT = noArgs,
        ZONE_CHANGED = noArgs,
        ZONE_CHANGED_NEW_AREA = noArgs,
        ZONE_CHANGED_INDOORS = noArgs,
        PLAYER_REGEN_DISABLED = noArgs,
        PLAYER_REGEN_ENABLED = noArgs,
        UNIT_AURA = { "unit", "info" },
        UNIT_POWER_UPDATE = { "unit", "type" },
        UNIT_HEALTH = { "unit" },
        BAG_UPDATE = { "bagID" },
        BAG_UPDATE_DELAYED = noArgs,
        BAG_UPDATE_COOLDOWN = noArgs,
        ITEM_LOCKED = itemLockCommonArgs,
        ITEM_LOCK_CHANGED = itemLockCommonArgs,
        ITEM_UNLOCKED = itemLockCommonArgs,
        GET_ITEM_INFO_RECEIVED = { "itemID", "success" },
        INVENTORY_SEARCH_UPDATE = noArgs,
        CHAT_MSG_SAY = {"message"},
        CHAT_MSG_YELL = {"message"},
        CHAT_MSG_WHISPER = {"message", "sender"},
        CHAT_MSG_PARTY = {"message"},
        CHAT_MSG_GUILD = {"message"},
        CHAT_MSG_OFFICER = {"message"},
        CHAT_MSG_RAID = {"message"},
        CHAT_MSG_SYSTEM = {"message"},
        ADDON_LOADED = {"name", "hasBindings"},
        VARIABLES_LOADED = noArgs,
        QUEST_ACCEPTED = {"questID"},
        QUEST_TURNED_IN = {"questID", "xp", "money"},
        QUEST_LOG_UPDATE = noArgs,
        QUEST_REMOVED = {"questID", "wasReplay"},
        QUEST_DETAIL = {"startItemID"},
        QUEST_COMPLETE = noArgs,
        QUEST_PROGRESS = noArgs,
        QUEST_GREETING = noArgs,
        QUEST_WATCH_LIST_CHANGED = {"questID", "added"},
        SUPER_TRACKING_CHANGED = noArgs,
        MERCHANT_SHOW = noArgs,
        MERCHANT_CLOSED = noArgs,
        MERCHANT_UPDATE = noArgs,
        MAIL_INBOX_UPDATE = noArgs,
        MAIL_SHOW = noArgs,
        MAIL_CLOSED = noArgs,
        AUCTION_HOUSE_SHOW = noArgs,
        AUCTION_HOUSE_CLOSED = noArgs,
        LOOT_OPENED = {"autoLoot", "isFromItem"},
        LOOT_CLOSED = noArgs,
        LOOT_READY = {"autoLoog"},
        START_LOOT_ROLL = {"rollID", "rollTime", "lootHandle"},
        TRADE_SHOW = noArgs,
        TRADE_CLOSED = noArgs,
        BANKFRAME_OPENED = noArgs,
        BANKFRAME_CLOSED = noArgs,
        PLAYERBANKSLOTS_CHANGED = {"slot"},
        PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED = {"slot"},
        TAXIMAP_OPENED = {"system"},
        TAXIMAP_CLOSED = noArgs,
        GOSSIP_SHOW = {"uiTextureKit"},
        GOSSIP_CLOSED = {"interactionIsContinuing"},
        TRADE_SKILL_SHOW = noArgs,
        TRADE_SKILL_CLOSE = noArgs,
        TRANSMOGRIFY_OPEN = noArgs,
        TRANSMOGRIFY_CLOSE = noArgs,
        TRANSMOGRIFY_SUCCESS = {"location"},
        TRANSMOGRIFY_UPDATE = noArgs,
        VIEWED_TRANSMOG_OUTFIT_CHANGED = noArgs,
        VIEWED_TRANSMOG_OUTFIT_SITUATIONS_CHANGED = noArgs,
        VIEWED_TRANSMOG_OUTFIT_SLOT_REFRESH = noArgs,
        VIEWED_TRANSMOG_OUTFIT_SLOT_SAVE_SUCCESS = {"slot", "type", "option"},
        TRANSMOG_SEARCH_UPDATED = {"searchType", "collectionType"},
        TRANSMOG_COLLECTION_UPDATED = {"collectionIdx", "modID", "itemAppearanceID", "reason"},
        ITEM_SEARCH_RESULTS_UPDATED = {"itemKey", "newAuctionID"},
        COMMODITY_SEARCH_RESULTS_UPDATED = {"itemID"},
        AUCTION_HOUSE_AUCTION_CREATED = {"auctionID"},
        AUCTION_HOUSE_THROTTLED_SYSTEM_READY = noArgs,
        BLACK_MARKET_OPEN = noArgs,
        BLACK_MARKET_BID_RESULT = {"marketID", "resultCode"},
        CRAFTINGORDERS_DISPLAY_CRAFTER_FULFILLED_MSG = {"orderTypeString", "itemNameString", "playerNameString", "tipAmount", "quantityCrafted"},
        PLAYER_MONEY = noArgs,
        PLAYER_DEAD = noArgs,
        PLAYER_UNGHOST = noArgs,
        PLAYER_EQUIPMENT_CHANGED = {"equipmentSlot", "hasCurrent"},
        UPDATE_INVENTORY_DURABILITY = noArgs,
        GUILDBANKFRAME_OPENED = noArgs,
        GUILDBANKFRAME_CLOSED = noArgs,
        GUILDBANK_UPDATE_MONEY = noArgs,
        GUILDBANKBAGSLOTS_CHANGED = noArgs,
        GUILDBANK_UPDATE_TABS = noArgs,
        TRADE_ACCEPT_UPDATE = {"playerAccepted", "targetAccepted"},
        TRADE_MONEY_CHANGED = noArgs,
        TRADE_PLAYER_ITEM_CHANGED = {"tradeSlotIdx"},
        TRADE_TARGET_ITEM_CHANGED = {"tradeSlotIdx"},
        UI_INFO_MESSAGE = {"errorType", "message"},
        UI_ERROR_MESSAGE = {"errorType", "message"},
        TRAIT_CONFIG_COMMIT_FAILED = noArgs,
        TRAIT_COND_INFO_CHANGED = {"condID"},
        TRAIT_CONFIG_CREATED = {"configInfo"},
        TRAIT_CONFIG_DELETED = {"configID"},
        TRAIT_CONFIG_LIST_UPDATED = noArgs,
        TRAIT_CONFIG_UPDATED = {"configID"},
        TRAIT_NODE_CHANGED = {"nodeID"},
        TRAIT_NODE_CHANGED_PARTIAL = {"ID", "info"},
        TRAIT_NODE_ENTRY_UPDATED = {"nodeEntryID"},
        TRAIT_SUB_TREE_CHANGED = {"subTreeID"},
        TRAIT_SYSTEM_INTERACTION_STARTED = {"treeID"},
        TRAIT_SYSTEM_NPC_CLOSED = noArgs,
        TRAIT_TREE_CHANGED = {"treeID"},
        TRAIT_TREE_CURRENCY_INFO_UPDATED = {"treeID"},
        TRY_PURCHASE_TO_NODE_PARTIAL_SUCCESS = {"nodeFinishedOn"},
        ACTIVE_COMBAT_CONFIG_CHANGED = {"configID"},
        SELECTED_LOADOUT_CHANGED = noArgs,
        SPECIALIZATION_CHANGE_CAST_FAILED = noArgs,
        STARTER_BUILD_ACTIVATION_FAILED = noArgs,
        TALENTS_INVOLUNTARILY_RESET = {"isPetTalents"},
        PORTRAITS_UPDATED = noArgs,
        PLAYER_LEVEL_UP = {"level", "healthDelta", "powerDelta", "numNewTalents", "numNewPvpTalentSlots", "strengthDelta", "agilityDelta", "staminaDelta", "intellectDelta", "spiritDelta"},
        PLAYER_TARGET_CHANGED = noArgs,
        UNIT_SPELLCAST_START = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_STOP = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_CHANNEL_START = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_CHANNEL_STOP = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_SUCCEEDED = unitSpellCastCommonArgs,
        SPELL_UPDATE_COOLDOWN = {"spellID", "baseSpellID", "category", "startRecoveryCategory"},
        SPELLS_CHANGED = noArgs,
        CHAT_MSG_CHANNEL = {"message"},
        BAG_OPEN = {"bagID"},
        BAG_CLOSED = {"bagID"},
        LOOT_SLOT_CHANGED = {"lootSlot"},
        GROUP_ROSTER_UPDATE = noArgs,
        PLAYER_SPECIALIZATION_CHANGED = {"unitTarget"},
        CURRENCY_DISPLAY_UPDATE = {"currencyType", "quantity", "quantityChange", "quantityGainSource", "destroyReason"},
        UPDATE_BINDINGS = noArgs,
        ENCOUNTER_START = {"encounterID", "encounterName", "difficultyID", "groupSize"},
        ENCOUNTER_END = {"encounterID", "encounterName", "difficultyID", "groupSize", "success"},
        UPDATE_INSTANCE_INFO = noArgs,
        WEEKLY_REWARDS_UPDATE = noArgs,
        NEW_RECIPE_LEARNED = {"recipeID", "recipeLevel", "baseRecipeID"},
        CHALLENGE_MODE_COMPLETED = noArgs,
        MOUNT_JOURNAL_USABILITY_CHANGED = noArgs,
    },

    -- Reference: https://warcraft.wiki.gg/wiki/Events
    COMMON_EVENTS = {
        "PLAYER_ENTERING_WORLD", "PLAYER_LEAVING_WORLD", "PLAYER_LOGIN", "PLAYER_LOGOUT",
        "ZONE_CHANGED", "ZONE_CHANGED_NEW_AREA", "ZONE_CHANGED_INDOORS",
        "PLAYER_REGEN_DISABLED", "PLAYER_REGEN_ENABLED",
        "UNIT_HEALTH", "UNIT_POWER_UPDATE", "UNIT_AURA",
        "BAG_UPDATE", "BAG_UPDATE_DELAYED", "BAG_UPDATE_COOLDOWN", "ITEM_LOCKED", "ITEM_LOCK_CHANGED", "ITEM_UNLOCKED",
        "GET_ITEM_INFO_RECEIVED", "INVENTORY_SEARCH_UPDATE",
        "CHAT_MSG_SAY", "CHAT_MSG_YELL", "CHAT_MSG_WHISPER", "CHAT_MSG_PARTY",
        "CHAT_MSG_GUILD", "CHAT_MSG_OFFICER", "CHAT_MSG_RAID", "CHAT_MSG_SYSTEM",
        "ADDON_LOADED", "VARIABLES_LOADED",
        "QUEST_ACCEPTED", "QUEST_TURNED_IN", "QUEST_LOG_UPDATE", "QUEST_REMOVED",
        "QUEST_DETAIL", "QUEST_COMPLETE", "QUEST_PROGRESS", "QUEST_GREETING",
        "QUEST_WATCH_LIST_CHANGED", "SUPER_TRACKING_CHANGED",
        "MERCHANT_SHOW", "MERCHANT_CLOSED", "MERCHANT_UPDATE",
        "MAIL_INBOX_UPDATE", "MAIL_SHOW", "MAIL_CLOSED",
        "AUCTION_HOUSE_SHOW", "AUCTION_HOUSE_CLOSED",
        "LOOT_OPENED", "LOOT_CLOSED", "LOOT_READY", "START_LOOT_ROLL",
        "TRADE_SHOW", "TRADE_CLOSED",
        "BANKFRAME_OPENED", "BANKFRAME_CLOSED",
        "PLAYERBANKSLOTS_CHANGED", "PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED",
        "TAXIMAP_OPENED", "TAXIMAP_CLOSED",
        "GOSSIP_SHOW", "GOSSIP_CLOSED",
        "TRADE_SKILL_SHOW", "TRADE_SKILL_CLOSE",
        "TRANSMOGRIFY_OPEN", "TRANSMOGRIFY_CLOSE", "TRANSMOGRIFY_SUCCESS", "TRANSMOGRIFY_UPDATE",
        "VIEWED_TRANSMOG_OUTFIT_CHANGED", "VIEWED_TRANSMOG_OUTFIT_SITUATIONS_CHANGED",
        "VIEWED_TRANSMOG_OUTFIT_SLOT_REFRESH", "VIEWED_TRANSMOG_OUTFIT_SLOT_SAVE_SUCCESS",
        "TRANSMOG_SEARCH_UPDATED", "TRANSMOG_COLLECTION_UPDATED",
        "ITEM_SEARCH_RESULTS_UPDATED", "COMMODITY_SEARCH_RESULTS_UPDATED",
        "AUCTION_HOUSE_AUCTION_CREATED", "AUCTION_HOUSE_THROTTLED_SYSTEM_READY",
        "BLACK_MARKET_OPEN", "BLACK_MARKET_BID_RESULT",
        "CRAFTINGORDERS_DISPLAY_CRAFTER_FULFILLED_MSG",
        "PLAYER_MONEY", "PLAYER_DEAD", "PLAYER_UNGHOST",
        "PLAYER_EQUIPMENT_CHANGED", "UPDATE_INVENTORY_DURABILITY",
        "GUILDBANKFRAME_OPENED", "GUILDBANKFRAME_CLOSED", "GUILDBANK_UPDATE_MONEY",
        "GUILDBANKBAGSLOTS_CHANGED", "GUILDBANK_UPDATE_TABS",
        "TRADE_ACCEPT_UPDATE", "TRADE_MONEY_CHANGED",
        "TRADE_PLAYER_ITEM_CHANGED", "TRADE_TARGET_ITEM_CHANGED",
        "UI_INFO_MESSAGE", "UI_ERROR_MESSAGE",
        "TRAIT_CONFIG_COMMIT_FAILED", "TRAIT_COND_INFO_CHANGED", "TRAIT_CONFIG_CREATED",
        "TRAIT_CONFIG_DELETED", "TRAIT_CONFIG_LIST_UPDATED", "TRAIT_CONFIG_UPDATED",
        "TRAIT_NODE_CHANGED", "TRAIT_NODE_CHANGED_PARTIAL", "TRAIT_NODE_ENTRY_UPDATED",
        "TRAIT_SUB_TREE_CHANGED", "TRAIT_SYSTEM_INTERACTION_STARTED", "TRAIT_SYSTEM_NPC_CLOSED",
        "TRAIT_TREE_CHANGED", "TRAIT_TREE_CURRENCY_INFO_UPDATED", "TRY_PURCHASE_TO_NODE_PARTIAL_SUCCESS",
        "ACTIVE_COMBAT_CONFIG_CHANGED", "SELECTED_LOADOUT_CHANGED", "SPECIALIZATION_CHANGE_CAST_FAILED",
        "STARTER_BUILD_ACTIVATION_FAILED", "TALENTS_INVOLUNTARILY_RESET",
        "PORTRAITS_UPDATED", "PLAYER_LEVEL_UP",
        "PLAYER_TARGET_CHANGED",
        "UNIT_SPELLCAST_START", "UNIT_SPELLCAST_STOP",
        "UNIT_SPELLCAST_CHANNEL_START", "UNIT_SPELLCAST_CHANNEL_STOP",
        "UNIT_SPELLCAST_SUCCEEDED",
        "SPELL_UPDATE_COOLDOWN", "SPELLS_CHANGED",
        "CHAT_MSG_CHANNEL",
        "BAG_OPEN", "BAG_CLOSED",
        "LOOT_SLOT_CHANGED",
        "GROUP_ROSTER_UPDATE",
        "PLAYER_SPECIALIZATION_CHANGED",
        "CURRENCY_DISPLAY_UPDATE",
        "UPDATE_BINDINGS",
        "ENCOUNTER_START", "ENCOUNTER_END",
        "UPDATE_INSTANCE_INFO", "WEEKLY_REWARDS_UPDATE", "NEW_RECIPE_LEARNED",
        "CHALLENGE_MODE_COMPLETED", "MOUNT_JOURNAL_USABILITY_CHANGED",
    },

    -- Preset hex swatches for Color Tools tab (display names via locale nameKey)
    COLOR_TOOLS_COMMON = {
        { hex = "FFFFFF", nameKey = "COLOR_TOOLS_NAME_WHITE" },
        { hex = "000000", nameKey = "COLOR_TOOLS_NAME_BLACK" },
        { hex = "FF0000", nameKey = "COLOR_TOOLS_NAME_RED" },
        { hex = "00FF00", nameKey = "COLOR_TOOLS_NAME_GREEN" },
        { hex = "0000FF", nameKey = "COLOR_TOOLS_NAME_BLUE" },
        { hex = "FFFF00", nameKey = "COLOR_TOOLS_NAME_YELLOW" },
        { hex = "00FFFF", nameKey = "COLOR_TOOLS_NAME_CYAN" },
        { hex = "FF00FF", nameKey = "COLOR_TOOLS_NAME_MAGENTA" },
        { hex = "FFA500", nameKey = "COLOR_TOOLS_NAME_ORANGE" },
        { hex = "800080", nameKey = "COLOR_TOOLS_NAME_PURPLE" },
        { hex = "FFD700", nameKey = "COLOR_TOOLS_NAME_GOLD" },
        { hex = "C0C0C0", nameKey = "COLOR_TOOLS_NAME_SILVER" },
    },

    -- Main window / cross-tab UI tuning
    DEVTOOL_UI = {
        MAIN_FRAME_DEFAULT_WIDTH = 750,
        MAIN_FRAME_DEFAULT_HEIGHT = 450,
        MAIN_FRAME_RESIZE_CAP = 0.95,
        TAB_GAP = 4,
        TAB_HEIGHT = 28,
        NUM_TABS = 8,
        TAB_INDEX_FRAME = 1,
        TAB_INDEX_EVENTS = 2,
        TAB_INDEX_LUA = 3,
        TAB_INDEX_TEXTURES = 4,
        TAB_INDEX_COLORS = 5,
        TAB_INDEX_LAYOUT = 6,
        TAB_INDEX_MONITOR = 7,
        TAB_INDEX_SETTINGS = 8,
        FRAME_INSPECTOR_LEFT_DEFAULT_WIDTH = 350,
        FRAME_INSPECTOR_LEFT_MIN_WIDTH = 350,
        FRAME_INSPECTOR_RIGHT_MIN_WIDTH = 300,
        FRAME_INSPECTOR_DIVIDER_WIDTH = 6,
        EVENT_SELECTOR_WIDTH = 600,
        EVENT_SELECTOR_HEIGHT = 500,
        EVENT_IMPORT_WIDTH = 650,
        EVENT_IMPORT_HEIGHT = 480,
        EVENT_MONITOR_MAX_ROWS = 201,
        MONITOR_LIST_ROW_HEIGHT = 20,
        MONITOR_MAX_ROWS = 60,
        TEXTURE_LIST_BUTTON_HEIGHT = 18,
        TEXTURE_PREVIEW_BASE_SIZE = 256,
        TEXTURE_ZOOM_IN_FACTOR = 1.2,
        TEXTURE_ZOOM_OUT_FACTOR = 0.8,
        TEXTURE_ZOOM_MIN = 0.25,
        TEXTURE_ZOOM_MAX = 4.0,
        COLOR_PICKER_PANEL_WIDTH = 280,
        COLOR_PICKER_PANEL_HEIGHT = 297,
        COLOR_CLASS_PANEL_MIN_WIDTH = 200,
        COLOR_TOOLS_PICKER_TOP_PADDING = 10,
        COLOR_TOOLS_PICKER_VERTICAL_GAP = 20,
        COLOR_TOOLS_ROW_HEIGHT = 25,
        COLOR_TOOLS_ROW_SPACING = 27,
    },

    -- Reference: https://warcraft.wiki.gg/wiki/Widget_script_handlers
    COMMON_SCRIPTS = {
        "OnAnimFinished", "OnAnimStarted", "OnArrowPressed", "OnAttributeChanged",
        "OnChar", "OnCharComposition", "OnClick", "OnColorSelect", "OnCooldownDone",
        "OnCursorChanged", "OnDisable", "OnDoubleClick", "OnDragStart", "OnDragStop",
        "OnDressModel", "OnEditFocusGained", "OnEditFocusLost", "OnEnable",
        "OnEnter", "OnEnterPressed", "OnEscapePressed", "OnEvent", "OnFinished",
        "OnGamePadButtonDown", "OnGamePadButtonUp", "OnGamePadStick",
        "OnHide", "OnHorizontalScroll", "OnHyperlinkClick", "OnHyperlinkEnter", "OnHyperlinkLeave",
        "OnInputLanguageChanged", "OnKeyDown", "OnKeyUp", "OnLeave", "OnLoad",
        "OnLoop", "OnMinMaxChanged", "OnModelCleared", "OnModelLoaded", "OnModelLoading",
        "OnMouseDown", "OnMouseUp", "OnMouseWheel", "OnMovieFinished", "OnPanFinished",
        "OnPause", "OnPlay", "OnReceiveDrag", "OnScrollRangeChanged", "OnShow",
        "OnSizeChanged", "OnSpacePressed", "OnStop", "OnTabPressed", "OnTextChanged",
        "OnTextSet", "OnTooltipCleared", "OnTooltipSetDefaultAnchor", "OnTooltipSetFramestack",
        "OnUiMapChanged", "OnUpdate", "OnValueChanged", "OnVerticalScroll",
        "PostClick", "PreClick",
    },
}
